export const INDUSTRIES = [
  "Agriculture",
  "Automotive",
  "Banking & Finance",
  "Construction",
  "Consulting",
  "Consumer Goods",
  "Education",
  "Energy & Utilities",
  "Entertainment & Media",
  "Food & Beverage",
  "Government",
  "Healthcare",
  "Hospitality & Tourism",
  "Information Technology",
  "Insurance",
  "Legal Services",
  "Manufacturing",
  "Marketing & Advertising",
  "Mining",
  "Non-Profit",
  "Real Estate",
  "Retail",
  "Telecommunications",
  "Transportation & Logistics",
  "Other"
];
