/**
 * Client-side PDF report generation (jspdf).
 *
 * Shared "Call Report" / "Meeting Report" builder used by the call & meeting
 * detail pages. Renders a clean document with the MetriCorex brand header
 * (/Assets/logo-mark.png), a two-column details block, attendees, AI notes
 * (summary, key points, decisions, action items, important timestamps) and a
 * speaker-grouped transcript.
 *
 * Layout rules:
 *  - Every text line advances by its REAL line height (~1.3 × font size).
 *  - Multi-line values wrap inside their own column; the row advances by the
 *    tallest column, so columns can never overlap.
 *  - Page breaks are checked with the true height of the upcoming block; the
 *    brand header is followed by "(cont.)" headers on every later page, and a
 *    "Generated by MetriCorex — <date> · Page X of Y" footer closes each page
 *    (total pages via jsPDF putTotalPages).
 *  - The header block follows a strict vertical rhythm: the "MetriCorex" title
 *    baseline sits at y+6 and its tagline at y+22, so the two never overlap.
 *
 * Data shape (GET /meetings/:id/report — backend server/routes/meetings.ts):
 *  - meeting carries scheduledAt/startedAt/endedAt (startTime/endTime are
 *    accepted as a legacy fallback but the API shape wins).
 *  - notes.importantTimestamps items are {ts, description} (the older
 *    {label, timestamp} shape and plain strings are still accepted).
 */
import { jsPDF } from "jspdf";
import { resolveMediaUrl } from "@/lib/media-url";

const BRAND_BLUE: [number, number, number] = [67, 83, 255]; // #4353FF
const INK: [number, number, number] = [17, 24, 39];
const MUTED: [number, number, number] = [107, 114, 128];
const LINE: [number, number, number] = [229, 231, 235];

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
/** Never print a raw user id where a human name belongs. */
function humanName(name?: string | null, fallback = "Participant"): string {
  const value = String(name || "").trim();
  if (!value || UUID_RE.test(value)) return fallback;
  return value;
}

/** Placeholder replaced with the real page count by doc.putTotalPages(). */
const TOTAL_PAGES_TOKEN = "{total_pages_count_string}";

/** Fetch a same-origin/absolute image and convert to a data URL (null on fail). */
async function loadImageDataUrl(url: string): Promise<string | null> {
  try {
    const res = await fetch(resolveMediaUrl(url), { mode: "cors" });
    if (!res.ok) return null;
    const blob = await res.blob();
    return await new Promise((resolve) => {
      const reader = new FileReader();
      reader.onload = () => resolve(typeof reader.result === "string" ? reader.result : null);
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

export function formatDuration(totalSeconds?: number | null): string {
  const secs = Math.max(0, Math.round(totalSeconds || 0));
  const h = Math.floor(secs / 3600);
  const m = Math.floor((secs % 3600) / 60);
  const s = secs % 60;
  const mm = h > 0 ? String(m).padStart(2, "0") : String(m);
  const ss = String(s).padStart(2, "0");
  return h > 0 ? `${h}:${mm}:${ss}` : `${m}:${ss}`;
}

export function fmtDateTime(value?: string | null): string {
  if (!value) return "—";
  const d = new Date(value);
  if (isNaN(d.getTime())) return "—";
  return d.toLocaleString(undefined, {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });
}

function fmtTime(value?: string | null): string {
  if (!value) return "";
  const d = new Date(value);
  if (isNaN(d.getTime())) return "";
  return d.toLocaleTimeString(undefined, { hour: "numeric", minute: "2-digit" });
}

/** Date part for subtitles — empty string (not "—") when unknown. */
function fmtDatePart(value?: string | null): string {
  if (!value) return "";
  const d = new Date(value);
  if (isNaN(d.getTime())) return "";
  return d.toLocaleString(undefined, {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });
}

/** Time only when the event shares a day with `ref`, else the full date-time. */
function fmtWhen(value?: string | null, ref?: Date | null): string {
  if (!value) return "";
  const d = new Date(value);
  if (isNaN(d.getTime())) return "";
  if (ref && !isNaN(ref.getTime()) && d.toDateString() === ref.toDateString()) {
    return d.toLocaleTimeString(undefined, { hour: "numeric", minute: "2-digit" });
  }
  return fmtDateTime(value);
}

interface DocCursor {
  doc: jsPDF;
  y: number;
  pageWidth: number;
  pageHeight: number;
  margin: number;
  pageNo: number;
  /** Drawn at the top of every page after the first ("… (cont.)"). */
  continuedHeader?: string | null;
}

/** Line height helper — 10pt text → 13pt leading. */
const leading = (fontSize: number) => fontSize * 1.3;

const CONTENT_BOTTOM = (ctx: DocCursor) => ctx.pageHeight - ctx.margin - 24;

function addFooter(ctx: DocCursor) {
  const { doc } = ctx;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...MUTED);
  const dateLabel = new Date().toLocaleDateString(undefined, {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
  doc.text(`Generated by MetriCorex — ${dateLabel}`, ctx.margin, ctx.pageHeight - ctx.margin + 4);
  doc.text(
    `Page ${ctx.pageNo} of ${TOTAL_PAGES_TOKEN}`,
    ctx.pageWidth - ctx.margin,
    ctx.pageHeight - ctx.margin + 4,
    { align: "right" },
  );
}

/** Start a new page with the "(cont.)" running header. */
function beginPage(ctx: DocCursor) {
  addFooter(ctx);
  ctx.doc.addPage();
  ctx.pageNo += 1;
  ctx.y = ctx.margin + 8;
  if (ctx.continuedHeader) {
    ctx.doc.setFont("helvetica", "normal");
    ctx.doc.setFontSize(9);
    ctx.doc.setTextColor(...MUTED);
    ctx.doc.text(ctx.continuedHeader, ctx.margin, ctx.y);
    ctx.y += 7;
    ctx.doc.setDrawColor(...LINE);
    ctx.doc.setLineWidth(0.6);
    ctx.doc.line(ctx.margin, ctx.y, ctx.pageWidth - ctx.margin, ctx.y);
    ctx.y += 16;
  }
}

/** Start a new page (footer + running header first), or stay put when `needed` still fits. */
function ensureSpace(ctx: DocCursor, needed: number) {
  if (ctx.y + needed > CONTENT_BOTTOM(ctx)) beginPage(ctx);
}

function sectionTitle(ctx: DocCursor, title: string) {
  // Title + its underline + the first content row must stay together.
  ensureSpace(ctx, 48);
  ctx.y += 10;
  ctx.doc.setFont("helvetica", "bold");
  ctx.doc.setFontSize(12);
  ctx.doc.setTextColor(...INK);
  ctx.doc.text(title, ctx.margin, ctx.y);
  ctx.y += 7;
  // Subtle full-width rule with a short brand accent on the left.
  ctx.doc.setDrawColor(...LINE);
  ctx.doc.setLineWidth(0.75);
  ctx.doc.line(ctx.margin, ctx.y, ctx.pageWidth - ctx.margin, ctx.y);
  ctx.doc.setDrawColor(...BRAND_BLUE);
  ctx.doc.setLineWidth(1.8);
  ctx.doc.line(ctx.margin, ctx.y, ctx.margin + 30, ctx.y);
  ctx.y += 13;
}

/** Key/value row — the value column wraps and the row grows to fit it. */
function kvRow(ctx: DocCursor, key: string, value: string) {
  const fontSize = 10;
  ctx.doc.setFont("helvetica", "normal");
  ctx.doc.setFontSize(fontSize);
  const keyX = ctx.margin;
  const valueX = ctx.margin + 120;
  const valueWidth = ctx.pageWidth - ctx.margin - valueX;
  const lines = ctx.doc.splitTextToSize(value || "—", valueWidth) as string[];
  const rowHeight = Math.max(1, lines.length) * leading(fontSize) + 5;
  ensureSpace(ctx, rowHeight);
  ctx.doc.setTextColor(...MUTED);
  ctx.doc.text(key, keyX, ctx.y);
  ctx.doc.setTextColor(...INK);
  ctx.doc.text(lines, valueX, ctx.y);
  ctx.y += rowHeight;
}

/** Wrapped paragraph at `indent`, advancing by real line heights. */
function wrapParagraph(ctx: DocCursor, text: string, indent = 0, fontSize = 10) {
  ctx.doc.setFont("helvetica", "normal");
  ctx.doc.setFontSize(fontSize);
  const lines = ctx.doc.splitTextToSize(
    text || "",
    ctx.pageWidth - ctx.margin * 2 - indent,
  ) as string[];
  for (const line of lines) {
    ensureSpace(ctx, leading(fontSize));
    ctx.doc.setFont("helvetica", "normal");
    ctx.doc.setFontSize(fontSize);
    ctx.doc.setTextColor(...INK);
    ctx.doc.text(line, ctx.margin + indent, ctx.y);
    ctx.y += leading(fontSize);
  }
}

/** Bulleted item with a hanging indent — bullet and text never overlap. */
function bulletItem(ctx: DocCursor, text: string, fontSize = 10) {
  ctx.doc.setFont("helvetica", "normal");
  ctx.doc.setFontSize(fontSize);
  const lines = ctx.doc.splitTextToSize(
    text || "",
    ctx.pageWidth - ctx.margin * 2 - 14,
  ) as string[];
  const blockHeight = lines.length * leading(fontSize);
  ensureSpace(ctx, Math.min(blockHeight, leading(fontSize) * 2));
  ctx.doc.setFont("helvetica", "normal");
  ctx.doc.setFontSize(fontSize);
  ctx.doc.setTextColor(...MUTED);
  ctx.doc.text("•", ctx.margin + 2, ctx.y);
  ctx.doc.setTextColor(...INK);
  for (const line of lines) {
    ctx.doc.text(line, ctx.margin + 14, ctx.y);
    ctx.y += leading(fontSize);
  }
}

async function brandHeader(doc: jsPDF, title: string, subtitle: string): Promise<DocCursor> {
  const margin = 40;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let y = margin;

  // Brand logo (best-effort — skipped if unavailable).
  const logo = await loadImageDataUrl("/Assets/logo-mark.png");
  const logoSize = 34;
  let textX = margin;
  if (logo) {
    try {
      doc.addImage(logo, "PNG", margin, y - 8, logoSize, logoSize);
      textX = margin + logoSize + 12;
    } catch {
      /* ignore malformed image */
    }
  }
  // Vertical rhythm: title baseline y+6, tagline baseline y+22 — the 16pt
  // title and the 9pt tagline can never collide (was y+4 / y+11 = overlap).
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(...BRAND_BLUE);
  doc.text("MetriCorex", textX, y + 6);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...MUTED);
  doc.text("business calls, meetings, chat and AI meeting notes", textX, y + 22);

  // Divider sits just below the 34px logo block.
  y += logoSize + 6;
  doc.setDrawColor(...LINE);
  doc.setLineWidth(0.8);
  doc.line(margin, y, pageWidth - margin, y);
  y += 20;

  // Title — wrap long meeting titles instead of letting them run off-page.
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...INK);
  const titleLines = doc.splitTextToSize(title, pageWidth - margin * 2) as string[];
  for (const line of titleLines) {
    doc.text(line, margin, y);
    y += leading(14);
  }
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  doc.setTextColor(...MUTED);
  const subtitleLines = doc.splitTextToSize(subtitle, pageWidth - margin * 2) as string[];
  for (const line of subtitleLines) {
    doc.text(line, margin, y);
    y += leading(9.5);
  }
  y += 6;

  return { doc, y, pageWidth, pageHeight, margin, pageNo: 1, continuedHeader: null };
}

// ==========================================
// Transcript de-noise (render-time cleanup)
// ==========================================

/**
 * Standalone filler tokens produced by raw ASR ("uh", "um", "uhh", "erm",
 * "hmm", plus the usual mm-hmm / uh-huh variants). Word-bounded and
 * case-insensitive so real words ("column", "summer") are never touched.
 */
const FILLER_TOKEN_RE =
  /\b(?:uh+|um+|uhm+|erm+|hmm+|mhm+|uh[- ]?huh+|mm[- ]?hmm+|um[- ]?hum+)\b/gi;

/**
 * Light, meaning-preserving cleanup for raw ASR segments: collapse repeated
 * whitespace, drop standalone filler tokens, collapse repeated punctuation
 * and re-attach punctuation to the preceding word. Never paraphrases.
 */
function cleanTranscriptText(input?: string | null): string {
  let text = String(input ?? "");
  if (!text.trim()) return "";
  // 1. Collapse repeated whitespace.
  text = text.replace(/\s+/g, " ").trim();
  // 2. Remove standalone filler tokens (case-insensitive, word-bounded).
  text = text.replace(FILLER_TOKEN_RE, "");
  text = text.replace(/\s+/g, " ").trim();
  // 3. Strip stray leading/trailing list dashes or bullets ("— hmm" → "…").
  text = text.replace(/^\s*[-–—•]\s+/, "").replace(/\s+[-–—•]$/, "");
  // 4. Collapse runs of repeated punctuation ("!!!", "?? ...", ", ,") to one mark.
  text = text.replace(/([,.;:!?])(?:[\s,]*\1)+/g, "$1");
  // 5. Re-attach punctuation to the preceding word (filler removal leaves gaps).
  text = text.replace(/\s+([,.;:!?])/g, "$1");
  // 6. Drop dangling punctuation left at the edges by filler removal.
  text = text.replace(/^[,.;:!?]+\s*/, "").replace(/\s*[,;:!?]+$/, "");
  return text.replace(/\s{2,}/g, " ").trim();
}

// ==========================================
// Transcript rendering (speaker-grouped)
// ==========================================

interface TranscriptSegment {
  id?: string;
  speakerName?: string | null;
  text: string;
  createdAt?: string | null;
}

const TRANSCRIPT_TIME_COL = 58; // width of the gray time column on the left

/** Cleaned transcript entries — segments that reduce to nothing are dropped. */
interface CleanSegment {
  segment: TranscriptSegment;
  text: string;
}

function cleanSegments(segments: TranscriptSegment[]): CleanSegment[] {
  const out: CleanSegment[] = [];
  for (const segment of segments || []) {
    const text = cleanTranscriptText(segment?.text);
    if (text) out.push({ segment, text });
  }
  return out;
}

/**
 * Transcript block: gray time on the left margin, speaker name (bold) on the
 * first line of each speaker group, body text in the right column. Consecutive
 * segments from the same speaker are grouped under one header.
 */
function drawTranscript(ctx: DocCursor, entries: CleanSegment[]) {
  const bodyX = ctx.margin + TRANSCRIPT_TIME_COL;
  const bodyWidth = ctx.pageWidth - ctx.margin - bodyX;
  const fontSize = 9.5;
  let prevSpeaker: string | null = null;

  for (const { segment, text } of entries) {
    const speaker = humanName(segment.speakerName, "Speaker");
    const sameSpeaker = prevSpeaker !== null && speaker.toLowerCase() === prevSpeaker;
    const time = fmtTime(segment.createdAt);

    // Keep the time + speaker header + first body line together.
    ensureSpace(ctx, leading(fontSize) * 2 + 6);
    ctx.y += sameSpeaker ? 3 : 7;

    // Gray time on the left column.
    if (time) {
      ctx.doc.setFont("helvetica", "normal");
      ctx.doc.setFontSize(8.5);
      ctx.doc.setTextColor(...MUTED);
      ctx.doc.text(time, ctx.margin, ctx.y);
    }
    // Speaker header only when the speaker changes (grouped).
    if (!sameSpeaker) {
      ctx.doc.setFont("helvetica", "bold");
      ctx.doc.setFontSize(fontSize);
      ctx.doc.setTextColor(...INK);
      ctx.doc.text(speaker, bodyX, ctx.y);
      ctx.y += leading(fontSize) + 2;
    }

    ctx.doc.setFont("helvetica", "normal");
    ctx.doc.setFontSize(fontSize);
    const lines = ctx.doc.splitTextToSize(text, bodyWidth) as string[];
    for (const line of lines) {
      ensureSpace(ctx, leading(fontSize));
      ctx.doc.setFont("helvetica", "normal");
      ctx.doc.setFontSize(fontSize);
      ctx.doc.setTextColor(...INK);
      ctx.doc.text(line, bodyX, ctx.y);
      ctx.y += leading(fontSize);
    }
    prevSpeaker = speaker.toLowerCase();
  }
}

function docSetFont(ctx: DocCursor, style: "bold" | "normal") {
  ctx.doc.setFont("helvetica", style);
  ctx.doc.setTextColor(...INK);
}

// ==========================================
// Call Report
// ==========================================

export interface CallReportData {
  call: {
    id: string;
    type?: string;
    status?: string;
    startedAt?: string | null;
    endedAt?: string | null;
    durationSeconds?: number | null;
    callCode?: string | null;
    isGroupCall?: boolean;
  };
  participants: Array<{
    userId?: string;
    name?: string | null;
    joinedAt?: string | null;
    leftAt?: string | null;
    durationSeconds?: number | null;
  }>;
  transcripts?: Array<{ id?: string; speakerName?: string | null; text: string; createdAt?: string | null }> | null;
  recording?: { storageUrl: string; duration?: number | null } | null;
  notes?: {
    summary?: string | null;
    keyPoints?: string[] | null;
    decisions?: string[] | null;
    actionItems?: Array<{ title?: string; task?: string; assignedTo?: string | null; ownerName?: string | null; dueDate?: string | null; status?: string }> | null;
    importantTimestamps?: Array<{ ts?: string; description?: string }> | null;
  } | null;
}

export async function buildCallReportPdf(data: CallReportData): Promise<jsPDF> {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const startedAt = data.call.startedAt || null;
  const subtitleParts = [
    `${data.call.type === "video" ? "Video" : "Audio"} call`,
    data.call.callCode || data.call.id || "",
    fmtDatePart(startedAt),
  ].filter(Boolean);
  const ctx = await brandHeader(doc, "Call Report", subtitleParts.join(" · "));
  ctx.continuedHeader = `Call Report (cont.)`;

  sectionTitle(ctx, "Details");
  kvRow(ctx, "Status", data.call.status || "—");
  kvRow(ctx, "Type", data.call.type === "video" ? "Video call" : "Audio call");
  kvRow(ctx, "Started", fmtDateTime(startedAt));
  kvRow(ctx, "Ended", fmtDateTime(data.call.endedAt));
  kvRow(ctx, "Duration", data.call.durationSeconds ? formatDuration(data.call.durationSeconds) : "—");
  kvRow(ctx, "Call code", data.call.callCode || "—");

  sectionTitle(ctx, `Participants (${data.participants.length})`);
  for (const p of data.participants) {
    const bits: string[] = [];
    if (p.joinedAt) bits.push(`joined ${fmtDateTime(p.joinedAt)}`);
    if (p.leftAt) bits.push(`left ${fmtDateTime(p.leftAt)}`);
    if (p.durationSeconds) bits.push(formatDuration(p.durationSeconds));
    const detail = bits.length ? bits.join(" · ") : "invited";
    const fontSize = 10;
    docSetFont(ctx, "bold");
    ctx.doc.setFontSize(fontSize);
    const nameX = ctx.margin;
    const detailX = ctx.margin + 170;
    const detailLines = ctx.doc.splitTextToSize(detail, ctx.pageWidth - ctx.margin - detailX) as string[];
    const rowHeight = Math.max(1, detailLines.length) * leading(fontSize) + 5;
    ensureSpace(ctx, rowHeight);
    ctx.doc.setFontSize(fontSize);
    ctx.doc.text(humanName(p.name, "Unknown"), nameX, ctx.y);
    docSetFont(ctx, "normal");
    ctx.doc.setTextColor(...MUTED);
    ctx.doc.text(detailLines, detailX, ctx.y);
    ctx.doc.setTextColor(...INK);
    ctx.y += rowHeight;
  }

  const notes = data.notes;
  if (notes && (notes.summary || (notes.actionItems && notes.actionItems.length > 0))) {
    sectionTitle(ctx, "AI Summary & Action Points");
    if (notes.summary) {
      docSetFont(ctx, "normal");
      wrapParagraph(ctx, notes.summary, 12);
      ctx.y += 4;
    }
    const keyPoints = (notes.keyPoints || []).filter(Boolean);
    if (keyPoints.length > 0) {
      docSetFont(ctx, "bold");
      ensureSpace(ctx, 20);
      ctx.doc.setFontSize(10);
      ctx.doc.text("Key points", ctx.margin, ctx.y);
      ctx.y += 15;
      docSetFont(ctx, "normal");
      for (const kp of keyPoints) bulletItem(ctx, kp);
      ctx.y += 4;
    }
    const decisions = (notes.decisions || []).filter(Boolean);
    if (decisions.length > 0) {
      docSetFont(ctx, "bold");
      ensureSpace(ctx, 20);
      ctx.doc.setFontSize(10);
      ctx.doc.text("Decisions", ctx.margin, ctx.y);
      ctx.y += 15;
      docSetFont(ctx, "normal");
      for (const d of decisions) bulletItem(ctx, d);
      ctx.y += 4;
    }
    const actionItems = (notes.actionItems || []).filter(Boolean);
    if (actionItems.length > 0) {
      docSetFont(ctx, "bold");
      ensureSpace(ctx, 20);
      ctx.doc.setFontSize(10);
      ctx.doc.text("Action points", ctx.margin, ctx.y);
      ctx.y += 15;
      docSetFont(ctx, "normal");
      for (const ai of actionItems) {
        // Never print a raw user id — an unresolved UUID owner is dropped.
        const ownerRaw = ai.ownerName || ai.assignedTo || "";
        const owner = UUID_RE.test(String(ownerRaw).trim()) ? "" : String(ownerRaw).trim();
        const label = `${ai.title || ai.task || "Action item"}${owner ? ` — by ${owner}` : ""}${ai.dueDate ? ` (due ${ai.dueDate})` : ""}`;
        bulletItem(ctx, label);
      }
    }
    const stamps = notes.importantTimestamps || [];
    if (stamps.length > 0) {
      docSetFont(ctx, "bold");
      ensureSpace(ctx, 20);
      ctx.doc.setFontSize(10);
      ctx.doc.text("Key moments", ctx.margin, ctx.y);
      ctx.y += 15;
      docSetFont(ctx, "normal");
      for (const s of stamps) {
        const ts = String(s?.ts || "").trim();
        const description = String(s?.description || "").trim();
        if (!ts && !description) continue;
        bulletItem(ctx, ts ? `${ts} — ${description}` : description, 9.5);
      }
    }
  }

  const cleanedTranscript = cleanSegments(data.transcripts || []);
  if (cleanedTranscript.length > 0) {
    sectionTitle(ctx, `Transcript (${cleanedTranscript.length})`);
    drawTranscript(ctx, cleanedTranscript);
  } else {
    sectionTitle(ctx, "Transcript");
    docSetFont(ctx, "normal");
    ctx.doc.setTextColor(...MUTED);
    ctx.doc.text("No transcript is available for this call.", ctx.margin, ctx.y);
    ctx.doc.setTextColor(...INK);
    ctx.y += 16;
  }

  if (data.recording?.storageUrl) {
    sectionTitle(ctx, "Recording");
    docSetFont(ctx, "normal");
    wrapParagraph(ctx, `Recording available: ${data.recording.storageUrl}`);
  }

  addFooter(ctx);
  doc.putTotalPages(TOTAL_PAGES_TOKEN);
  return doc;
}

// ==========================================
// Meeting Report
// ==========================================

export interface MeetingReportData {
  meeting?: {
    id?: string;
    title?: string;
    description?: string | null;
    status?: string;
    // API shape (GET /meetings/:id/report).
    scheduledAt?: string | null;
    startedAt?: string | null;
    endedAt?: string | null;
    durationSeconds?: number | null;
    meetingCode?: string | null;
    timezone?: string | null;
    // Legacy/alternate shape — accepted, but the API shape above wins.
    startTime?: string | null;
    endTime?: string | null;
  } | null;
  attendees?: Array<{
    userId?: string;
    name?: string | null;
    email?: string | null;
    avatarUrl?: string | null;
    joinedAt?: string | null;
    leftAt?: string | null;
    status?: string;
  }> | null;
  notes?: {
    summary?: string | null;
    keyPoints?: string[] | string | null;
    decisions?: string[] | string | null;
    actionItems?: Array<{
      title?: string;
      task?: string;
      description?: string | null;
      ownerName?: string | null;
      assignedTo?: string | null;
      dueDate?: string | null;
      status?: string;
    }> | null;
    importantTimestamps?:
      | Array<{ ts?: string; description?: string; label?: string; timestamp?: string }>
      | string[]
      | null;
  } | null;
  transcripts?: Array<{ id?: string; speakerName?: string | null; text: string; createdAt?: string | null }> | null;
  recordings?: Array<{ id?: string; storageUrl?: string; duration?: number | null }> | null;
}

/** Meeting start: API shape (startedAt/scheduledAt) first, legacy startTime second. */
function pickMeetingStart(m?: MeetingReportData["meeting"]): string | null {
  return m?.startedAt || m?.scheduledAt || m?.startTime || null;
}

/** Meeting end: API shape (endedAt) first, legacy endTime second. */
function pickMeetingEnd(m?: MeetingReportData["meeting"]): string | null {
  return m?.endedAt || m?.endTime || null;
}

/**
 * Display status derived from the lifecycle timestamps: ended → Completed,
 * started (not ended) → Ongoing, otherwise the raw meeting status (prettified,
 * e.g. "scheduled" → "Scheduled"). An explicitly cancelled meeting keeps its
 * status even when a start exists (lifecycle aborted, never completed).
 */
function displayMeetingStatus(m?: MeetingReportData["meeting"], start?: string | null, end?: string | null): string {
  const prettify = (value: string) =>
    value.replace(/[_-]+/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
  if (end) return "Completed";
  const raw = String(m?.status || "").trim();
  // A cancelled meeting never completed — keep its real status.
  if (/^cancell?ed$/i.test(raw.replace(/[\s_-]+/g, ""))) return prettify(raw);
  if (start) return "Ongoing";
  if (!raw) return "—";
  return prettify(raw);
}

/**
 * Important timestamps accept every stored shape:
 *  - AI notes: {ts, description}
 *  - legacy builder shape: {label, timestamp}
 *  - plain strings
 */
function normalizeTimestamps(
  notes?: MeetingReportData["notes"] | null,
): Array<{ ts: string; description: string }> {
  const stamps = (notes as { importantTimestamps?: unknown } | null | undefined)?.importantTimestamps;
  if (!Array.isArray(stamps)) return [];
  const out: Array<{ ts: string; description: string }> = [];
  for (const raw of stamps as Array<unknown>) {
    if (raw == null) continue;
    if (typeof raw === "string") {
      const description = raw.trim();
      if (description) out.push({ ts: "", description });
      continue;
    }
    if (typeof raw === "object") {
      const rec = raw as Record<string, unknown>;
      const ts = String(rec.ts ?? rec.timestamp ?? rec.time ?? "").trim();
      const description = String(rec.description ?? rec.label ?? rec.text ?? "").trim();
      if (ts || description) out.push({ ts, description });
    }
  }
  return out;
}

function toStringList(value: string[] | string | null | undefined): string[] {
  if (!value) return [];
  if (Array.isArray(value)) return value.map((v) => (typeof v === "string" ? v : JSON.stringify(v)));
  if (typeof value === "string") {
    return value
      .split(/\n|(?:^|\s)-\s/)
      .map((s) => s.trim())
      .filter(Boolean);
  }
  return [];
}

export async function buildMeetingReportPdf(data: MeetingReportData): Promise<jsPDF> {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const m = data.meeting || {};
  const start = pickMeetingStart(m);
  const end = pickMeetingEnd(m);
  const startDate = start ? new Date(start) : null;
  const title = m.title || "Meeting";

  // Subtitle next to the room code — date omitted (not "—") until known.
  const subtitleParts = [title, m.meetingCode || m.id || "", fmtDatePart(start)].filter(Boolean);
  const ctx = await brandHeader(doc, "Meeting Report", subtitleParts.join(" · "));
  ctx.continuedHeader = `Meeting Report — ${title} (cont.)`;

  // ---------------- Details (two-column key/value block) ----------------
  sectionTitle(ctx, "Details");
  kvRow(ctx, "Title", title);
  kvRow(ctx, "Status", displayMeetingStatus(m, start, end));
  kvRow(ctx, "Start", fmtDateTime(start));
  kvRow(ctx, "End", fmtDateTime(end));
  if (m.durationSeconds) kvRow(ctx, "Duration", formatDuration(m.durationSeconds));
  kvRow(ctx, "Room code", m.meetingCode || m.id || "—");
  if (m.timezone) kvRow(ctx, "Timezone", String(m.timezone));
  if (m.description) kvRow(ctx, "Description", String(m.description));

  // ---------------- Attendees (bulleted, with join/leave times) ----------------
  const attendees = data.attendees || [];
  sectionTitle(ctx, `Attendees (${attendees.length})`);
  if (attendees.length === 0) {
    docSetFont(ctx, "normal");
    ctx.doc.setTextColor(...MUTED);
    ctx.doc.text("No attendees recorded.", ctx.margin, ctx.y);
    ctx.doc.setTextColor(...INK);
    ctx.y += 16;
  }
  for (const a of attendees) {
    const name = humanName(a.name, "Attendee");
    const email = a.email && !UUID_RE.test(String(a.email).trim()) ? ` (${String(a.email).trim()})` : "";
    const bits: string[] = [];
    if (a.joinedAt) bits.push(`joined ${fmtWhen(a.joinedAt, startDate)}`);
    if (a.leftAt) bits.push(`left ${fmtWhen(a.leftAt, startDate)}`);
    const detail = bits.join(" · ");
    const fontSize = 10;
    const blockHeight = leading(fontSize) + (detail ? leading(9) : 0) + 3;
    ensureSpace(ctx, blockHeight);
    // Bullet + bold name (+ muted email) on the first line.
    ctx.doc.setFont("helvetica", "normal");
    ctx.doc.setFontSize(fontSize);
    ctx.doc.setTextColor(...MUTED);
    ctx.doc.text("•", ctx.margin + 2, ctx.y);
    ctx.doc.setFont("helvetica", "bold");
    ctx.doc.setFontSize(fontSize);
    ctx.doc.setTextColor(...INK);
    ctx.doc.text(name, ctx.margin + 14, ctx.y);
    if (email) {
      const nameWidth = ctx.doc.getTextWidth(name);
      ctx.doc.setFont("helvetica", "normal");
      ctx.doc.setFontSize(9.5);
      ctx.doc.setTextColor(...MUTED);
      ctx.doc.text(email, ctx.margin + 14 + nameWidth + 4, ctx.y);
    }
    ctx.y += leading(fontSize);
    // Join/leave timeline in gray on the second line.
    if (detail) {
      ctx.doc.setFont("helvetica", "normal");
      ctx.doc.setFontSize(9);
      ctx.doc.setTextColor(...MUTED);
      ctx.doc.text(detail, ctx.margin + 14, ctx.y);
      ctx.y += leading(9);
    }
    ctx.y += 3;
  }

  // ---------------- AI notes ----------------
  const notes = data.notes || {};
  const summary = notes.summary;
  if (summary) {
    sectionTitle(ctx, "AI Summary");
    docSetFont(ctx, "normal");
    wrapParagraph(ctx, summary);
    ctx.y += 4;
  }

  const keyPoints = toStringList(notes.keyPoints);
  if (keyPoints.length > 0) {
    sectionTitle(ctx, "Key Points");
    docSetFont(ctx, "normal");
    for (const kp of keyPoints) bulletItem(ctx, kp);
    ctx.y += 4;
  }

  const decisions = toStringList(notes.decisions);
  if (decisions.length > 0) {
    sectionTitle(ctx, "Decisions");
    docSetFont(ctx, "normal");
    for (const d of decisions) bulletItem(ctx, d);
    ctx.y += 4;
  }

  const actionItems = notes.actionItems || [];
  if (actionItems.length > 0) {
    sectionTitle(ctx, "Action Items");
    // Two-column table: Task (wraps) | Owner (wraps) — row height = tallest cell.
    const taskX = ctx.margin;
    const taskWidth = 290;
    const ownerX = ctx.margin + 310;
    const ownerWidth = ctx.pageWidth - ctx.margin - ownerX;
    docSetFont(ctx, "bold");
    ctx.doc.setFontSize(9.5);
    ctx.doc.text("Task", taskX, ctx.y);
    ctx.doc.text("Owner", ownerX, ctx.y);
    ctx.y += 5;
    ctx.doc.setDrawColor(...LINE);
    ctx.doc.setLineWidth(0.6);
    ctx.doc.line(ctx.margin, ctx.y, ctx.pageWidth - ctx.margin, ctx.y);
    ctx.y += 11;
    for (const ai of actionItems) {
      // AI notes use {title, description}; older rows may carry {task}.
      const taskLabel = String(ai.task || ai.title || ai.description || "Action item");
      const due = ai.dueDate ? ` (due ${String(ai.dueDate)})` : "";
      const ownerRaw = String(ai.ownerName || ai.assignedTo || "").trim();
      const owner = UUID_RE.test(ownerRaw) || !ownerRaw ? "Unassigned" : ownerRaw;
      ctx.doc.setFont("helvetica", "normal");
      ctx.doc.setFontSize(9.5);
      const taskLines = ctx.doc.splitTextToSize(`${taskLabel}${due}`, taskWidth) as string[];
      const ownerLines = ctx.doc.splitTextToSize(owner, ownerWidth) as string[];
      const rowHeight = Math.max(taskLines.length, ownerLines.length) * leading(9.5) + 5;
      ensureSpace(ctx, rowHeight);
      docSetFont(ctx, "normal");
      ctx.doc.setFontSize(9.5);
      ctx.doc.text(taskLines, taskX, ctx.y);
      ctx.doc.setTextColor(...MUTED);
      ctx.doc.text(ownerLines, ownerX, ctx.y);
      ctx.doc.setTextColor(...INK);
      ctx.y += rowHeight;
    }
  }

  const stamps = normalizeTimestamps(notes);
  if (stamps.length > 0) {
    sectionTitle(ctx, "Important Timestamps");
    docSetFont(ctx, "normal");
    for (const s of stamps) {
      // "• 10:22 PM — description"
      bulletItem(ctx, s.ts ? `${s.ts} — ${s.description}` : s.description, 9.5);
    }
  }

  // ---------------- Transcript (cleaned, speaker-grouped) ----------------
  const cleanedTranscript = cleanSegments(data.transcripts || []);
  if (cleanedTranscript.length > 0) {
    sectionTitle(ctx, `Transcript (${cleanedTranscript.length})`);
    drawTranscript(ctx, cleanedTranscript);
  } else if ((data.transcripts || []).length > 0) {
    sectionTitle(ctx, "Transcript");
    docSetFont(ctx, "normal");
    ctx.doc.setTextColor(...MUTED);
    ctx.doc.text("Transcript segments contained no usable speech.", ctx.margin, ctx.y);
    ctx.doc.setTextColor(...INK);
    ctx.y += 16;
  }

  // ---------------- Recordings ----------------
  const recordings = data.recordings || [];
  if (recordings.length > 0) {
    sectionTitle(ctx, "Recordings");
    docSetFont(ctx, "normal");
    for (const r of recordings) {
      if (r?.storageUrl) {
        const dur = r.duration ? ` · ${formatDuration(r.duration)}` : "";
        wrapParagraph(ctx, `Recording: ${r.storageUrl}${dur}`);
      }
    }
  }

  addFooter(ctx);
  doc.putTotalPages(TOTAL_PAGES_TOKEN);
  return doc;
}

/** Convenience: build + trigger a browser download. */
export async function downloadPdf(doc: jsPDF, filename: string): Promise<void> {
  doc.save(filename);
}
