/**
 * Client-side PDF report generation (jspdf).
 *
 * Shared "Call Report" / "Meeting Report" builder used by the call & meeting
 * detail pages. Renders a clean document with the MetriCorex brand header
 * (/Assets/logo-mark.png), a meta table, participants and the transcript.
 *
 * Layout rules (fix for the earlier overlapping-text bug):
 *  - Every text line advances by its REAL line height (~1.3 × font size).
 *  - Multi-line values wrap inside their own column; the row advances by the
 *    tallest column, so columns can never overlap.
 *  - Page breaks are checked with the true height of the upcoming block, and
 *    section titles always keep at least their first content row with them.
 */
import { jsPDF } from "jspdf";
import { resolveMediaUrl } from "@/lib/media-url";

const BRAND_BLUE: [number, number, number] = [67, 83, 255]; // #4353FF
const INK: [number, number, number] = [17, 24, 39];
const MUTED: [number, number, number] = [107, 114, 128];
const LINE: [number, number, number] = [229, 231, 235];

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
/** Never print a raw user id where a human name belongs. */
function humanName(name?: string | null, fallback = "Participant"): string {
  const value = String(name || "").trim();
  if (!value || UUID_RE.test(value)) return fallback;
  return value;
}

/** Fetch a same-origin/absolute image and convert to a data URL (null on fail). */
async function loadImageDataUrl(url: string): Promise<string | null> {
  try {
    const res = await fetch(resolveMediaUrl(url), { mode: "cors" });
    if (!res.ok) return null;
    const blob = await res.blob();
    return await new Promise((resolve) => {
      const reader = new FileReader();
      reader.onload = () => resolve(typeof reader.result === "string" ? reader.result : null);
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

export function formatDuration(totalSeconds?: number | null): string {
  const secs = Math.max(0, Math.round(totalSeconds || 0));
  const h = Math.floor(secs / 3600);
  const m = Math.floor((secs % 3600) / 60);
  const s = secs % 60;
  const mm = h > 0 ? String(m).padStart(2, "0") : String(m);
  const ss = String(s).padStart(2, "0");
  return h > 0 ? `${h}:${mm}:${ss}` : `${m}:${ss}`;
}

export function fmtDateTime(value?: string | null): string {
  if (!value) return "—";
  const d = new Date(value);
  if (isNaN(d.getTime())) return "—";
  return d.toLocaleString(undefined, {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });
}

interface DocCursor {
  doc: jsPDF;
  y: number;
  pageWidth: number;
  pageHeight: number;
  margin: number;
  pageNo: number;
}

/** Line height helper — 10pt text → 13pt leading. */
const leading = (fontSize: number) => fontSize * 1.3;

const CONTENT_BOTTOM = (ctx: DocCursor) => ctx.pageHeight - ctx.margin - 24;

function addFooter(ctx: DocCursor) {
  const { doc } = ctx;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...MUTED);
  doc.text(
    "Generated by MetriCorex — " + new Date().toLocaleString(),
    ctx.margin,
    ctx.pageHeight - ctx.margin + 4,
  );
  doc.text(
    `Page ${ctx.pageNo}`,
    ctx.pageWidth - ctx.margin,
    ctx.pageHeight - ctx.margin + 4,
    { align: "right" },
  );
}

/** Start a new page (footer first), or stay put when `needed` still fits. */
function ensureSpace(ctx: DocCursor, needed: number) {
  if (ctx.y + needed > CONTENT_BOTTOM(ctx)) {
    addFooter(ctx);
    ctx.doc.addPage();
    ctx.pageNo += 1;
    ctx.y = ctx.margin + 10;
  }
}

function sectionTitle(ctx: DocCursor, title: string) {
  // Title + its underline + the first content row must stay together.
  ensureSpace(ctx, 44);
  ctx.y += 10;
  ctx.doc.setFont("helvetica", "bold");
  ctx.doc.setFontSize(12);
  ctx.doc.setTextColor(...INK);
  ctx.doc.text(title, ctx.margin, ctx.y);
  ctx.y += 5;
  ctx.doc.setDrawColor(...BRAND_BLUE);
  ctx.doc.setLineWidth(1);
  ctx.doc.line(ctx.margin, ctx.y, ctx.margin + 42, ctx.y);
  ctx.y += 12;
}

/** Key/value row — the value column wraps and the row grows to fit it. */
function kvRow(ctx: DocCursor, key: string, value: string) {
  const fontSize = 10;
  ctx.doc.setFont("helvetica", "normal");
  ctx.doc.setFontSize(fontSize);
  const valueX = ctx.margin + 120;
  const valueWidth = ctx.pageWidth - ctx.margin - valueX;
  const lines = ctx.doc.splitTextToSize(value || "—", valueWidth) as string[];
  const rowHeight = Math.max(1, lines.length) * leading(fontSize) + 4;
  ensureSpace(ctx, rowHeight);
  ctx.doc.setTextColor(...MUTED);
  ctx.doc.text(key, ctx.margin, ctx.y);
  ctx.doc.setTextColor(...INK);
  ctx.doc.text(lines, valueX, ctx.y);
  ctx.y += rowHeight;
}

/** Wrapped paragraph at `indent`, advancing by real line heights. */
function wrapParagraph(ctx: DocCursor, text: string, indent = 0, fontSize = 10) {
  ctx.doc.setFontSize(fontSize);
  const lines = ctx.doc.splitTextToSize(
    text || "",
    ctx.pageWidth - ctx.margin * 2 - indent,
  ) as string[];
  for (const line of lines) {
    ensureSpace(ctx, leading(fontSize));
    ctx.doc.setFontSize(fontSize);
    ctx.doc.setTextColor(...INK);
    ctx.doc.text(line, ctx.margin + indent, ctx.y);
    ctx.y += leading(fontSize);
  }
}

/** Bulleted item with a hanging indent — bullet and text never overlap. */
function bulletItem(ctx: DocCursor, text: string, fontSize = 10) {
  ctx.doc.setFontSize(fontSize);
  const lines = ctx.doc.splitTextToSize(
    text || "",
    ctx.pageWidth - ctx.margin * 2 - 14,
  ) as string[];
  const blockHeight = lines.length * leading(fontSize);
  ensureSpace(ctx, Math.min(blockHeight, leading(fontSize) * 2));
  ctx.doc.setFontSize(fontSize);
  ctx.doc.setTextColor(...INK);
  ctx.doc.text("•", ctx.margin + 2, ctx.y);
  for (const line of lines) {
    ctx.doc.text(line, ctx.margin + 14, ctx.y);
    ctx.y += leading(fontSize);
  }
}

async function brandHeader(doc: jsPDF, title: string, subtitle: string): Promise<DocCursor> {
  const margin = 40;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let y = margin;

  // Brand logo (best-effort — skipped if unavailable).
  const logo = await loadImageDataUrl("/Assets/logo-mark.png");
  const logoSize = 34;
  let textX = margin;
  if (logo) {
    try {
      doc.addImage(logo, "PNG", margin, y - 6, logoSize, logoSize);
      textX = margin + logoSize + 10;
    } catch {
      /* ignore malformed image */
    }
  }
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(...BRAND_BLUE);
  doc.text("MetriCorex", textX, y + 4);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...MUTED);
  doc.text("business calls, meetings, chat and AI meeting notes", textX, y + 11);

  y += logoSize + 6;
  doc.setDrawColor(...LINE);
  doc.setLineWidth(0.8);
  doc.line(margin, y, pageWidth - margin, y);
  y += 16;

  // Title — wrap long meeting titles instead of letting them run off-page.
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...INK);
  const titleLines = doc.splitTextToSize(title, pageWidth - margin * 2) as string[];
  for (const line of titleLines) {
    doc.text(line, margin, y);
    y += leading(14);
  }
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  doc.setTextColor(...MUTED);
  const subtitleLines = doc.splitTextToSize(subtitle, pageWidth - margin * 2) as string[];
  for (const line of subtitleLines) {
    doc.text(line, margin, y);
    y += leading(9.5);
  }
  y += 6;

  return { doc, y, pageWidth, pageHeight, margin, pageNo: 1 };
}

// ==========================================
// Call Report
// ==========================================

export interface CallReportData {
  call: {
    id: string;
    type?: string;
    status?: string;
    startedAt?: string | null;
    endedAt?: string | null;
    durationSeconds?: number | null;
    callCode?: string | null;
    isGroupCall?: boolean;
  };
  participants: Array<{
    userId?: string;
    name?: string | null;
    joinedAt?: string | null;
    leftAt?: string | null;
    durationSeconds?: number | null;
  }>;
  transcripts?: Array<{ id?: string; speakerName?: string | null; text: string; createdAt?: string | null }> | null;
  recording?: { storageUrl: string; duration?: number | null } | null;
  notes?: {
    summary?: string | null;
    keyPoints?: string[] | null;
    decisions?: string[] | null;
    actionItems?: Array<{ title?: string; task?: string; assignedTo?: string | null; ownerName?: string | null; dueDate?: string | null; status?: string }> | null;
    importantTimestamps?: Array<{ ts?: string; description?: string }> | null;
  } | null;
}

export async function buildCallReportPdf(data: CallReportData): Promise<jsPDF> {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const ctx = await brandHeader(
    doc,
    "Call Report",
    `${data.call.type === "video" ? "Video" : "Audio"} call · ${data.call.callCode || data.call.id} · ${fmtDateTime(
      data.call.startedAt,
    )}`,
  );

  sectionTitle(ctx, "Details");
  kvRow(ctx, "Status", data.call.status || "—");
  kvRow(ctx, "Type", data.call.type === "video" ? "Video call" : "Audio call");
  kvRow(ctx, "Started", fmtDateTime(data.call.startedAt));
  kvRow(ctx, "Ended", fmtDateTime(data.call.endedAt));
  kvRow(ctx, "Duration", data.call.durationSeconds ? formatDuration(data.call.durationSeconds) : "—");
  kvRow(ctx, "Call code", data.call.callCode || "—");

  sectionTitle(ctx, `Participants (${data.participants.length})`);
  for (const p of data.participants) {
    const bits: string[] = [];
    if (p.joinedAt) bits.push(`joined ${fmtDateTime(p.joinedAt)}`);
    if (p.leftAt) bits.push(`left ${fmtDateTime(p.leftAt)}`);
    if (p.durationSeconds) bits.push(formatDuration(p.durationSeconds));
    const detail = bits.length ? bits.join(" · ") : "invited";
    const fontSize = 10;
    docSetFont(ctx, "bold");
    ctx.doc.setFontSize(fontSize);
    const nameX = ctx.margin;
    const detailX = ctx.margin + 170;
    const detailLines = ctx.doc.splitTextToSize(detail, ctx.pageWidth - ctx.margin - detailX) as string[];
    const rowHeight = Math.max(1, detailLines.length) * leading(fontSize) + 5;
    ensureSpace(ctx, rowHeight);
    ctx.doc.setFontSize(fontSize);
    ctx.doc.text(humanName(p.name, "Unknown"), nameX, ctx.y);
    docSetFont(ctx, "normal");
    ctx.doc.setTextColor(...MUTED);
    ctx.doc.text(detailLines, detailX, ctx.y);
    ctx.doc.setTextColor(...INK);
    ctx.y += rowHeight;
  }

  const notes = data.notes;
  if (notes && (notes.summary || (notes.actionItems && notes.actionItems.length > 0))) {
    sectionTitle(ctx, "AI Summary & Action Points");
    if (notes.summary) {
      docSetFont(ctx, "normal");
      wrapParagraph(ctx, notes.summary, 12);
      ctx.y += 4;
    }
    const keyPoints = (notes.keyPoints || []).filter(Boolean);
    if (keyPoints.length > 0) {
      docSetFont(ctx, "bold");
      ensureSpace(ctx, 20);
      ctx.doc.setFontSize(10);
      ctx.doc.text("Key points", ctx.margin, ctx.y);
      ctx.y += 15;
      docSetFont(ctx, "normal");
      for (const kp of keyPoints) bulletItem(ctx, kp);
      ctx.y += 4;
    }
    const decisions = (notes.decisions || []).filter(Boolean);
    if (decisions.length > 0) {
      docSetFont(ctx, "bold");
      ensureSpace(ctx, 20);
      ctx.doc.setFontSize(10);
      ctx.doc.text("Decisions", ctx.margin, ctx.y);
      ctx.y += 15;
      docSetFont(ctx, "normal");
      for (const d of decisions) bulletItem(ctx, d);
      ctx.y += 4;
    }
    const actionItems = (notes.actionItems || []).filter(Boolean);
    if (actionItems.length > 0) {
      docSetFont(ctx, "bold");
      ensureSpace(ctx, 20);
      ctx.doc.setFontSize(10);
      ctx.doc.text("Action points", ctx.margin, ctx.y);
      ctx.y += 15;
      docSetFont(ctx, "normal");
      for (const ai of actionItems) {
        // Never print a raw user id — an unresolved UUID owner is dropped.
        const ownerRaw = ai.ownerName || ai.assignedTo || "";
        const owner = UUID_RE.test(String(ownerRaw).trim()) ? "" : String(ownerRaw).trim();
        const label = `${ai.title || ai.task || "Action item"}${owner ? ` — by ${owner}` : ""}${ai.dueDate ? ` (due ${ai.dueDate})` : ""}`;
        bulletItem(ctx, label);
      }
    }
  }

  const transcripts = data.transcripts || [];
  if (transcripts.length > 0) {
    sectionTitle(ctx, `Transcript (${transcripts.length})`);
    for (const t of transcripts) {
      const time = t.createdAt
        ? new Date(t.createdAt).toLocaleTimeString(undefined, { hour: "numeric", minute: "2-digit" })
        : "";
      docSetFont(ctx, "bold");
      ensureSpace(ctx, 34); // speaker label + first body line stay together
      ctx.doc.setFontSize(9.5);
      ctx.doc.text(`${humanName(t.speakerName, "Speaker")}${time ? ` · ${time}` : ""}`, ctx.margin, ctx.y);
      ctx.y += leading(9.5) + 2;
      docSetFont(ctx, "normal");
      wrapParagraph(ctx, t.text, 12);
      ctx.y += 5;
    }
  } else {
    sectionTitle(ctx, "Transcript");
    docSetFont(ctx, "normal");
    ctx.doc.setTextColor(...MUTED);
    ctx.doc.text("No transcript is available for this call.", ctx.margin, ctx.y);
    ctx.doc.setTextColor(...INK);
    ctx.y += 16;
  }

  if (data.recording?.storageUrl) {
    sectionTitle(ctx, "Recording");
    docSetFont(ctx, "normal");
    wrapParagraph(ctx, `Recording available: ${data.recording.storageUrl}`);
  }

  addFooter(ctx);
  return doc;
}

function docSetFont(ctx: DocCursor, style: "bold" | "normal") {
  ctx.doc.setFont("helvetica", style);
  ctx.doc.setTextColor(...INK);
}

// ==========================================
// Meeting Report
// ==========================================

export interface MeetingReportData {
  meeting?: {
    id?: string;
    title?: string;
    status?: string;
    startTime?: string | null;
    endTime?: string | null;
    meetingCode?: string | null;
  } | null;
  attendees?: Array<{ userId?: string; name?: string | null; email?: string | null; avatarUrl?: string | null }> | null;
  notes?: {
    summary?: string | null;
    keyPoints?: string[] | string | null;
    decisions?: string[] | string | null;
    actionItems?: Array<{ task: string; ownerName?: string | null; assignedTo?: string | null }> | null;
    importantTimestamps?: Array<{ label?: string; timestamp?: string }> | string[] | null;
  } | null;
  transcripts?: Array<{ id?: string; speakerName?: string | null; text: string; createdAt?: string | null }> | null;
  recordings?: Array<{ id?: string; storageUrl?: string; duration?: number | null }> | null;
}

function toStringList(value: string[] | string | null | undefined): string[] {
  if (!value) return [];
  if (Array.isArray(value)) return value.map((v) => (typeof v === "string" ? v : JSON.stringify(v)));
  if (typeof value === "string") {
    return value
      .split(/\n|(?:^|\s)-\s/)
      .map((s) => s.trim())
      .filter(Boolean);
  }
  return [];
}

export async function buildMeetingReportPdf(data: MeetingReportData): Promise<jsPDF> {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const ctx = await brandHeader(
    doc,
    "Meeting Report",
    `${data.meeting?.title || "Meeting"} · ${data.meeting?.meetingCode || data.meeting?.id || ""} · ${fmtDateTime(
      data.meeting?.startTime,
    )}`,
  );

  sectionTitle(ctx, "Details");
  kvRow(ctx, "Title", data.meeting?.title || "Meeting");
  kvRow(ctx, "Status", data.meeting?.status || "—");
  kvRow(ctx, "Start", fmtDateTime(data.meeting?.startTime));
  kvRow(ctx, "End", fmtDateTime(data.meeting?.endTime));

  const attendees = data.attendees || [];
  sectionTitle(ctx, `Attendees (${attendees.length})`);
  if (attendees.length === 0) {
    docSetFont(ctx, "normal");
    ctx.doc.setTextColor(...MUTED);
    ctx.doc.text("No attendees recorded.", ctx.margin, ctx.y);
    ctx.doc.setTextColor(...INK);
    ctx.y += 16;
  }
  for (const a of attendees) {
    const fontSize = 10;
    const label = `${humanName(a.name, "Attendee")}${a.email ? ` (${a.email})` : ""}`;
    ctx.doc.setFont("helvetica", "normal");
    ctx.doc.setFontSize(fontSize);
    const lines = ctx.doc.splitTextToSize(label, ctx.pageWidth - ctx.margin * 2) as string[];
    ensureSpace(ctx, lines.length * leading(fontSize));
    ctx.doc.setTextColor(...INK);
    ctx.doc.text(lines, ctx.margin, ctx.y);
    ctx.y += lines.length * leading(fontSize) + 2;
  }

  const notes = data.notes || {};
  const summary = notes.summary;
  if (summary) {
    sectionTitle(ctx, "AI Summary");
    docSetFont(ctx, "normal");
    wrapParagraph(ctx, summary);
    ctx.y += 4;
  }

  const keyPoints = toStringList(notes.keyPoints);
  if (keyPoints.length > 0) {
    sectionTitle(ctx, "Key Points");
    docSetFont(ctx, "normal");
    for (const kp of keyPoints) bulletItem(ctx, kp);
    ctx.y += 4;
  }

  const decisions = toStringList(notes.decisions);
  if (decisions.length > 0) {
    sectionTitle(ctx, "Decisions");
    docSetFont(ctx, "normal");
    for (const d of decisions) bulletItem(ctx, d);
    ctx.y += 4;
  }

  const actionItems = notes.actionItems || [];
  if (actionItems.length > 0) {
    sectionTitle(ctx, "Action Items");
    // Two-column table: Task (wraps) | Owner (wraps) — row height = tallest cell.
    const taskX = ctx.margin;
    const taskWidth = 290;
    const ownerX = ctx.margin + 310;
    const ownerWidth = ctx.pageWidth - ctx.margin - ownerX;
    docSetFont(ctx, "bold");
    ctx.doc.setFontSize(9.5);
    ctx.doc.text("Task", taskX, ctx.y);
    ctx.doc.text("Owner", ownerX, ctx.y);
    ctx.y += 5;
    ctx.doc.setDrawColor(...LINE);
    ctx.doc.line(ctx.margin, ctx.y, ctx.pageWidth - ctx.margin, ctx.y);
    ctx.y += 11;
    for (const ai of actionItems) {
      const ownerRaw = ai.ownerName || ai.assignedTo || "";
      const owner = UUID_RE.test(String(ownerRaw).trim()) ? "Unassigned" : String(ownerRaw).trim() || "Unassigned";
      ctx.doc.setFont("helvetica", "normal");
      ctx.doc.setFontSize(9.5);
      const taskLines = ctx.doc.splitTextToSize(ai.task || "", taskWidth) as string[];
      const ownerLines = ctx.doc.splitTextToSize(owner, ownerWidth) as string[];
      const rowHeight = Math.max(taskLines.length, ownerLines.length) * leading(9.5) + 5;
      ensureSpace(ctx, rowHeight);
      docSetFont(ctx, "normal");
      ctx.doc.setFontSize(9.5);
      ctx.doc.text(taskLines, taskX, ctx.y);
      ctx.doc.setTextColor(...MUTED);
      ctx.doc.text(ownerLines, ownerX, ctx.y);
      ctx.doc.setTextColor(...INK);
      ctx.y += rowHeight;
    }
  }

  const stamps = notes.importantTimestamps;
  if (Array.isArray(stamps) && stamps.length > 0) {
    sectionTitle(ctx, "Important Timestamps");
    docSetFont(ctx, "normal");
    for (const s of stamps as any[]) {
      const label = typeof s === "string" ? s : s?.label || "";
      const ts = typeof s === "string" ? "" : s?.timestamp || "";
      bulletItem(ctx, `${ts ? `[${ts}] ` : ""}${label}`, 9.5);
    }
  }

  const transcripts = data.transcripts || [];
  if (transcripts.length > 0) {
    sectionTitle(ctx, `Transcript (${transcripts.length})`);
    for (const t of transcripts) {
      const time = t.createdAt
        ? new Date(t.createdAt).toLocaleTimeString(undefined, { hour: "numeric", minute: "2-digit" })
        : "";
      docSetFont(ctx, "bold");
      ensureSpace(ctx, 34); // speaker label + first body line stay together
      ctx.doc.setFontSize(9.5);
      ctx.doc.text(`${humanName(t.speakerName, "Speaker")}${time ? ` · ${time}` : ""}`, ctx.margin, ctx.y);
      ctx.y += leading(9.5) + 2;
      docSetFont(ctx, "normal");
      wrapParagraph(ctx, t.text, 12);
      ctx.y += 5;
    }
  }

  const recordings = data.recordings || [];
  if (recordings.length > 0) {
    sectionTitle(ctx, "Recordings");
    docSetFont(ctx, "normal");
    for (const r of recordings) {
      if (r?.storageUrl) wrapParagraph(ctx, `Recording: ${r.storageUrl}`);
    }
  }

  addFooter(ctx);
  return doc;
}

/** Convenience: build + trigger a browser download. */
export async function downloadPdf(doc: jsPDF, filename: string): Promise<void> {
  doc.save(filename);
}
