/**
 * Client-side PDF report generation (jspdf).
 *
 * Shared "Call Report" / "Meeting Report" builder used by the call & meeting
 * detail pages. Renders a clean document with the MetriCorex brand header
 * (/Assets/logo-mark.png), a meta table, participants and the transcript.
 */
import { jsPDF } from "jspdf";
import { resolveMediaUrl } from "@/lib/media-url";

const BRAND_BLUE: [number, number, number] = [67, 83, 255]; // #4353FF
const INK: [number, number, number] = [17, 24, 39];
const MUTED: [number, number, number] = [107, 114, 128];
const LINE: [number, number, number] = [229, 231, 235];

/** Fetch a same-origin/absolute image and convert to a data URL (null on fail). */
async function loadImageDataUrl(url: string): Promise<string | null> {
  try {
    const res = await fetch(resolveMediaUrl(url), { mode: "cors" });
    if (!res.ok) return null;
    const blob = await res.blob();
    return await new Promise((resolve) => {
      const reader = new FileReader();
      reader.onload = () => resolve(typeof reader.result === "string" ? reader.result : null);
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

export function formatDuration(totalSeconds?: number | null): string {
  const secs = Math.max(0, Math.round(totalSeconds || 0));
  const h = Math.floor(secs / 3600);
  const m = Math.floor((secs % 3600) / 60);
  const s = secs % 60;
  const mm = h > 0 ? String(m).padStart(2, "0") : String(m);
  const ss = String(s).padStart(2, "0");
  return h > 0 ? `${h}:${mm}:${ss}` : `${m}:${ss}`;
}

export function fmtDateTime(value?: string | null): string {
  if (!value) return "—";
  const d = new Date(value);
  if (isNaN(d.getTime())) return "—";
  return d.toLocaleString(undefined, {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });
}

interface DocCursor {
  doc: jsPDF;
  y: number;
  pageWidth: number;
  pageHeight: number;
  margin: number;
}

function ensureSpace(ctx: DocCursor, needed: number) {
  if (ctx.y + needed > ctx.pageHeight - ctx.margin - 20) {
    addFooter(ctx);
    ctx.doc.addPage();
    ctx.y = ctx.margin + 10;
  }
}

function addFooter(ctx: DocCursor) {
  const { doc } = ctx;
  doc.setFontSize(8);
  doc.setTextColor(...MUTED);
  doc.text(
    "Generated by MetriCorex — " + new Date().toLocaleString(),
    ctx.margin,
    ctx.pageHeight - ctx.margin + 4,
  );
}

function sectionTitle(ctx: DocCursor, title: string) {
  ensureSpace(ctx, 34);
  ctx.y += 8;
  ctx.doc.setFont("helvetica", "bold");
  ctx.doc.setFontSize(12);
  ctx.doc.setTextColor(...INK);
  ctx.doc.text(title, ctx.margin, ctx.y);
  ctx.y += 4;
  ctx.doc.setDrawColor(...BRAND_BLUE);
  ctx.doc.setLineWidth(1);
  ctx.doc.line(ctx.margin, ctx.y, ctx.margin + 42, ctx.y);
  ctx.y += 10;
}

function kvRow(ctx: DocCursor, key: string, value: string) {
  ensureSpace(ctx, 16);
  ctx.doc.setFont("helvetica", "normal");
  ctx.doc.setFontSize(10);
  ctx.doc.setTextColor(...MUTED);
  ctx.doc.text(key, ctx.margin, ctx.y);
  ctx.doc.setTextColor(...INK);
  const lines = ctx.doc.splitTextToSize(value || "—", ctx.pageWidth - ctx.margin * 2 - 110) as string[];
  ctx.doc.text(lines, ctx.margin + 110, ctx.y);
  ctx.y += Math.max(8, lines.length * 5) + 4;
}

function wrapParagraph(ctx: DocCursor, text: string, indent = 0) {
  const lines = ctx.doc.splitTextToSize(text || "", ctx.pageWidth - ctx.margin * 2 - indent) as string[];
  for (const line of lines) {
    ensureSpace(ctx, 14);
    ctx.doc.setFontSize(10);
    ctx.doc.setTextColor(...INK);
    ctx.doc.text(line, ctx.margin + indent, ctx.y);
    ctx.y += 5.5;
  }
  ctx.y += 3;
}

async function brandHeader(doc: jsPDF, title: string, subtitle: string): Promise<DocCursor> {
  const margin = 40;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let y = margin;

  // Brand logo (best-effort — skipped if unavailable).
  const logo = await loadImageDataUrl("/Assets/logo-mark.png");
  const logoSize = 34;
  let textX = margin;
  if (logo) {
    try {
      doc.addImage(logo, "PNG", margin, y - 6, logoSize, logoSize);
      textX = margin + logoSize + 10;
    } catch {
      /* ignore malformed image */
    }
  }
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(...BRAND_BLUE);
  doc.text("MetriCorex", textX, y + 4);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...MUTED);
  doc.text("business calls, meetings, chat and AI meeting notes", textX, y + 11);

  y += logoSize + 6;
  doc.setDrawColor(...LINE);
  doc.setLineWidth(0.8);
  doc.line(margin, y, pageWidth - margin, y);
  y += 14;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...INK);
  doc.text(title, margin, y);
  y += 7;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  doc.setTextColor(...MUTED);
  doc.text(subtitle, margin, y);
  y += 10;

  return { doc, y, pageWidth, pageHeight, margin };
}

// ==========================================
// Call Report
// ==========================================

export interface CallReportData {
  call: {
    id: string;
    type?: string;
    status?: string;
    startedAt?: string | null;
    endedAt?: string | null;
    durationSeconds?: number | null;
    callCode?: string | null;
    isGroupCall?: boolean;
  };
  participants: Array<{
    userId?: string;
    name?: string | null;
    joinedAt?: string | null;
    leftAt?: string | null;
    durationSeconds?: number | null;
  }>;
  transcripts?: Array<{ id?: string; speakerName?: string | null; text: string; createdAt?: string | null }> | null;
  recording?: { storageUrl: string; duration?: number | null } | null;
  notes?: {
    summary?: string | null;
    keyPoints?: string[] | null;
    decisions?: string[] | null;
    actionItems?: Array<{ title?: string; task?: string; assignedTo?: string | null; ownerName?: string | null; dueDate?: string | null; status?: string }> | null;
    importantTimestamps?: Array<{ ts?: string; description?: string }> | null;
  } | null;
}

export async function buildCallReportPdf(data: CallReportData): Promise<jsPDF> {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const ctx = await brandHeader(
    doc,
    "Call Report",
    `${data.call.type === "video" ? "Video" : "Audio"} call · ${data.call.callCode || data.call.id} · ${fmtDateTime(
      data.call.startedAt,
    )}`,
  );

  sectionTitle(ctx, "Details");
  kvRow(ctx, "Status", data.call.status || "—");
  kvRow(ctx, "Type", data.call.type === "video" ? "Video call" : "Audio call");
  kvRow(ctx, "Started", fmtDateTime(data.call.startedAt));
  kvRow(ctx, "Ended", fmtDateTime(data.call.endedAt));
  kvRow(ctx, "Duration", data.call.durationSeconds ? formatDuration(data.call.durationSeconds) : "—");
  kvRow(ctx, "Call code", data.call.callCode || "—");

  sectionTitle(ctx, `Participants (${data.participants.length})`);
  for (const p of data.participants) {
    ensureSpace(ctx, 18);
    docSetFont(ctx, "bold");
    ctx.doc.text(p.name || "Unknown", ctx.margin, ctx.y);
    docSetFont(ctx, "normal");
    ctx.doc.setTextColor(...MUTED);
    const bits: string[] = [];
    if (p.joinedAt) bits.push(`joined ${fmtDateTime(p.joinedAt)}`);
    if (p.leftAt) bits.push(`left ${fmtDateTime(p.leftAt)}`);
    if (p.durationSeconds) bits.push(formatDuration(p.durationSeconds));
    ctx.doc.text(bits.length ? bits.join(" · ") : "invited", ctx.margin + 170, ctx.y);
    ctx.doc.setTextColor(...INK);
    ctx.y += 16;
  }

  const notes = data.notes;
  if (notes && (notes.summary || (notes.actionItems && notes.actionItems.length > 0))) {
    sectionTitle(ctx, "AI Summary & Action Points");
    if (notes.summary) {
      docSetFont(ctx, "normal");
      wrapParagraph(ctx, notes.summary, 12);
    }
    const keyPoints = (notes.keyPoints || []).filter(Boolean);
    if (keyPoints.length > 0) {
      docSetFont(ctx, "bold");
      ensureSpace(ctx, 18);
      ctx.doc.text("Key points", ctx.margin, ctx.y);
      ctx.y += 14;
      docSetFont(ctx, "normal");
      for (const kp of keyPoints) wrapParagraph(ctx, `• ${kp}`, 4);
    }
    const decisions = (notes.decisions || []).filter(Boolean);
    if (decisions.length > 0) {
      docSetFont(ctx, "bold");
      ensureSpace(ctx, 18);
      ctx.doc.text("Decisions", ctx.margin, ctx.y);
      ctx.y += 14;
      docSetFont(ctx, "normal");
      for (const d of decisions) wrapParagraph(ctx, `• ${d}`, 4);
    }
    const actionItems = (notes.actionItems || []).filter(Boolean);
    if (actionItems.length > 0) {
      docSetFont(ctx, "bold");
      ensureSpace(ctx, 18);
      ctx.doc.text("Action points", ctx.margin, ctx.y);
      ctx.y += 14;
      docSetFont(ctx, "normal");
      for (const ai of actionItems) {
        const owner = ai.ownerName || ai.assignedTo || null;
        const label = `• ${ai.title || ai.task || "Action item"}${owner ? ` — by ${owner}` : ""}${ai.dueDate ? ` (due ${ai.dueDate})` : ""}`;
        wrapParagraph(ctx, label, 4);
      }
    }
  }

  const transcripts = data.transcripts || [];
  if (transcripts.length > 0) {
    sectionTitle(ctx, `Transcript (${transcripts.length})`);
    for (const t of transcripts) {
      const time = t.createdAt
        ? new Date(t.createdAt).toLocaleTimeString(undefined, { hour: "numeric", minute: "2-digit" })
        : "";
      docSetFont(ctx, "bold");
      ensureSpace(ctx, 20);
      ctx.doc.setFontSize(9.5);
      ctx.doc.text(`${t.speakerName || "Speaker"}${time ? ` · ${time}` : ""}`, ctx.margin, ctx.y);
      ctx.y += 12;
      docSetFont(ctx, "normal");
      wrapParagraph(ctx, t.text, 12);
    }
  } else {
    sectionTitle(ctx, "Transcript");
    docSetFont(ctx, "normal");
    ctx.doc.setTextColor(...MUTED);
    ctx.doc.text("No transcript is available for this call.", ctx.margin, ctx.y);
    ctx.doc.setTextColor(...INK);
    ctx.y += 16;
  }

  if (data.recording?.storageUrl) {
    sectionTitle(ctx, "Recording");
    docSetFont(ctx, "normal");
    wrapParagraph(ctx, `Recording available: ${data.recording.storageUrl}`);
  }

  addFooter(ctx);
  return doc;
}

function docSetFont(ctx: DocCursor, style: "bold" | "normal") {
  ctx.doc.setFont("helvetica", style);
  ctx.doc.setTextColor(...INK);
}

// ==========================================
// Meeting Report
// ==========================================

export interface MeetingReportData {
  meeting?: {
    id?: string;
    title?: string;
    status?: string;
    startTime?: string | null;
    endTime?: string | null;
    meetingCode?: string | null;
  } | null;
  attendees?: Array<{ userId?: string; name?: string | null; email?: string | null }> | null;
  notes?: {
    summary?: string | null;
    keyPoints?: string[] | string | null;
    decisions?: string[] | string | null;
    actionItems?: Array<{ task: string; ownerName?: string | null }> | null;
    importantTimestamps?: Array<{ label?: string; timestamp?: string }> | string[] | null;
  } | null;
  transcripts?: Array<{ id?: string; speakerName?: string | null; text: string; createdAt?: string | null }> | null;
  recordings?: Array<{ storageUrl?: string; duration?: number | null }> | null;
}

function toStringList(value: string[] | string | null | undefined): string[] {
  if (!value) return [];
  if (Array.isArray(value)) return value.map((v) => (typeof v === "string" ? v : JSON.stringify(v)));
  if (typeof value === "string") {
    return value
      .split(/\n|(?:^|\s)-\s/)
      .map((s) => s.trim())
      .filter(Boolean);
  }
  return [];
}

export async function buildMeetingReportPdf(data: MeetingReportData): Promise<jsPDF> {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const ctx = await brandHeader(
    doc,
    "Meeting Report",
    `${data.meeting?.title || "Meeting"} · ${data.meeting?.meetingCode || data.meeting?.id || ""} · ${fmtDateTime(
      data.meeting?.startTime,
    )}`,
  );

  sectionTitle(ctx, "Details");
  kvRow(ctx, "Title", data.meeting?.title || "Meeting");
  kvRow(ctx, "Status", data.meeting?.status || "—");
  kvRow(ctx, "Start", fmtDateTime(data.meeting?.startTime));
  kvRow(ctx, "End", fmtDateTime(data.meeting?.endTime));

  const attendees = data.attendees || [];
  sectionTitle(ctx, `Attendees (${attendees.length})`);
  if (attendees.length === 0) {
    docSetFont(ctx, "normal");
    ctx.doc.setTextColor(...MUTED);
    ctx.doc.text("No attendees recorded.", ctx.margin, ctx.y);
    ctx.doc.setTextColor(...INK);
    ctx.y += 16;
  }
  for (const a of attendees) {
    ensureSpace(ctx, 16);
    docSetFont(ctx, "normal");
    ctx.doc.text(`${a.name || "Attendee"}${a.email ? ` (${a.email})` : ""}`, ctx.margin, ctx.y);
    ctx.y += 15;
  }

  const notes = data.notes || {};
  const summary = notes.summary;
  if (summary) {
    sectionTitle(ctx, "AI Summary");
    docSetFont(ctx, "normal");
    wrapParagraph(ctx, summary);
  }

  const keyPoints = toStringList(notes.keyPoints);
  if (keyPoints.length > 0) {
    sectionTitle(ctx, "Key Points");
    for (const kp of keyPoints) {
      ensureSpace(ctx, 16);
      docSetFont(ctx, "normal");
      ctx.doc.text("•", ctx.margin + 2, ctx.y);
      wrapParagraph(ctx, kp, 14);
    }
  }

  const decisions = toStringList(notes.decisions);
  if (decisions.length > 0) {
    sectionTitle(ctx, "Decisions");
    for (const d of decisions) {
      ensureSpace(ctx, 16);
      docSetFont(ctx, "normal");
      ctx.doc.text("•", ctx.margin + 2, ctx.y);
      wrapParagraph(ctx, d, 14);
    }
  }

  const actionItems = notes.actionItems || [];
  if (actionItems.length > 0) {
    sectionTitle(ctx, "Action Items");
    // Simple table header
    docSetFont(ctx, "bold");
    ctx.doc.setFontSize(9.5);
    ctx.doc.text("Task", ctx.margin, ctx.y);
    ctx.doc.text("Owner", ctx.margin + 300, ctx.y);
    ctx.y += 4;
    ctx.doc.setDrawColor(...LINE);
    ctx.doc.line(ctx.margin, ctx.y, ctx.pageWidth - ctx.margin, ctx.y);
    ctx.y += 10;
    for (const ai of actionItems) {
      ensureSpace(ctx, 18);
      docSetFont(ctx, "normal");
      ctx.doc.setFontSize(9.5);
      const taskLines = ctx.doc.splitTextToSize(ai.task || "", 280) as string[];
      ctx.doc.text(taskLines, ctx.margin, ctx.y);
      ctx.doc.setTextColor(...MUTED);
      ctx.doc.text(ai.ownerName || "Unassigned", ctx.margin + 300, ctx.y);
      ctx.doc.setTextColor(...INK);
      ctx.y += Math.max(14, taskLines.length * 12);
    }
  }

  const stamps = notes.importantTimestamps;
  if (Array.isArray(stamps) && stamps.length > 0) {
    sectionTitle(ctx, "Important Timestamps");
    for (const s of stamps as any[]) {
      const label = typeof s === "string" ? s : s?.label || "";
      const ts = typeof s === "string" ? "" : s?.timestamp || "";
      ensureSpace(ctx, 16);
      docSetFont(ctx, "normal");
      ctx.doc.text(`${ts ? `[${ts}] ` : ""}${label}`, ctx.margin, ctx.y);
      ctx.y += 15;
    }
  }

  const transcripts = data.transcripts || [];
  if (transcripts.length > 0) {
    sectionTitle(ctx, `Transcript (${transcripts.length})`);
    for (const t of transcripts) {
      const time = t.createdAt
        ? new Date(t.createdAt).toLocaleTimeString(undefined, { hour: "numeric", minute: "2-digit" })
        : "";
      docSetFont(ctx, "bold");
      ensureSpace(ctx, 20);
      ctx.doc.setFontSize(9.5);
      ctx.doc.text(`${t.speakerName || "Speaker"}${time ? ` · ${time}` : ""}`, ctx.margin, ctx.y);
      ctx.y += 12;
      docSetFont(ctx, "normal");
      wrapParagraph(ctx, t.text, 12);
    }
  }

  const recordings = data.recordings || [];
  if (recordings.length > 0) {
    sectionTitle(ctx, "Recordings");
    for (const r of recordings) {
      if (r?.storageUrl) wrapParagraph(ctx, `Recording: ${r.storageUrl}`);
    }
  }

  addFooter(ctx);
  return doc;
}

/** Convenience: build + trigger a browser download. */
export async function downloadPdf(doc: jsPDF, filename: string): Promise<void> {
  doc.save(filename);
}
